# Generated by Django 3.1.1 on 2020-09-16 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('artist', models.CharField(max_length=64)),
                ('genre', models.CharField(choices=[('rock', 'Rock'), ('pop', 'Pop'), ('blues', 'Blues'), ('jazz', 'Jazz'), ('rockandroll', 'Rock&Roll'), ('folk', 'Folk'), ('hiphop', 'Hip Hop'), ('dance', 'Dance'), ('others', 'Others')], max_length=32)),
                ('cover', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albums',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('artist', models.CharField(max_length=64)),
                ('genre', models.CharField(choices=[('rock', 'Rock'), ('pop', 'Pop'), ('blues', 'Blues'), ('jazz', 'Jazz'), ('rockandroll', 'Rock&Roll'), ('folk', 'Folk'), ('hiphop', 'Hip Hop'), ('dance', 'Dance'), ('others', 'Others')], max_length=32)),
                ('album', models.CharField(max_length=64)),
                ('cover', models.FileField(upload_to='')),
                ('song_file', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name': 'Song',
                'verbose_name_plural': 'Songs',
            },
        ),
    ]
