# Generated by Django 3.1.7 on 2021-03-24 11:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, verbose_name='Album')),
                ('genre', models.CharField(choices=[('rock', 'Rock'), ('pop', 'Pop'), ('blues', 'Blues'), ('jazz', 'Jazz'), ('rockandroll', 'Rock&Roll'), ('folk', 'Folk'), ('hiphop', 'Hip Hop'), ('dance', 'Dance'), ('others', 'Others')], max_length=32, verbose_name='Genre')),
                ('pub_year', models.IntegerField(verbose_name='Publication year')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='album_cover/', verbose_name='Album cover')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albums',
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, verbose_name='Artist')),
                ('genre', models.CharField(choices=[('rock', 'Rock'), ('pop', 'Pop'), ('blues', 'Blues'), ('jazz', 'Jazz'), ('rockandroll', 'Rock&Roll'), ('folk', 'Folk'), ('hiphop', 'Hip Hop'), ('dance', 'Dance'), ('others', 'Others')], max_length=32, verbose_name='Genre')),
                ('create_year', models.IntegerField(verbose_name='Creation year')),
                ('picture', models.ImageField(default='artist_picture/default-artist-placeholder.png', upload_to='artist_picture', verbose_name='Artist Picture')),
                ('description', models.TextField(blank=True, default='', max_length=500, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Artist',
                'verbose_name_plural': 'Artists',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Song')),
                ('genre', models.CharField(choices=[('rock', 'Rock'), ('pop', 'Pop'), ('blues', 'Blues'), ('jazz', 'Jazz'), ('rockandroll', 'Rock&Roll'), ('folk', 'Folk'), ('hiphop', 'Hip Hop'), ('dance', 'Dance'), ('others', 'Others')], max_length=32, verbose_name='Genre')),
                ('pub_year', models.IntegerField(verbose_name='Publication year')),
                ('popularity', models.IntegerField(default=0, verbose_name='Number of song plays')),
                ('src', models.FileField(blank=True, null=True, upload_to='song_file', verbose_name='Song file')),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='songs.album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='songs.artist')),
            ],
            options={
                'verbose_name': 'Song',
                'verbose_name_plural': 'Songs',
            },
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='songs.artist'),
        ),
    ]
