# Generated by Django 3.1.1 on 2020-09-16 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('genre', models.CharField(choices=[('rock', 'Rock'), ('pop', 'Pop'), ('blues', 'Blues'), ('jazz', 'Jazz'), ('rockandroll', 'Rock&Roll'), ('folk', 'Folk'), ('hiphop', 'Hip Hop'), ('dance', 'Dance'), ('others', 'Others')], max_length=32)),
                ('create_year', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(default='')),
            ],
            options={
                'verbose_name': 'Artist',
                'verbose_name_plural': 'Artists',
            },
        ),
        migrations.AddField(
            model_name='album',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='album',
            name='pub_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='pub_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs.album'),
        ),
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs.artist'),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs.artist'),
        ),
    ]
