# Generated by Django 3.1.7 on 2021-03-24 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='ID',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='ID',
            new_name='id',
        ),
    ]
