# Generated by Django 3.1.1 on 2020-09-16 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_auto_20200916_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='description',
            field=models.TextField(default='lol'),
        ),
    ]
