# Generated by Django 3.1.1 on 2020-09-23 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0005_auto_20200916_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='cover',
        ),
    ]
