# Generated by Django 3.2 on 2021-04-20 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0005_auto_20210420_2003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersongs',
            old_name='song',
            new_name='songs',
        ),
    ]
