# Generated by Django 3.1.1 on 2020-09-29 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0007_auto_20200929_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='pub_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='artist',
            name='create_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='songs.album'),
        ),
        migrations.AlterField(
            model_name='song',
            name='pub_year',
            field=models.IntegerField(),
        ),
    ]
