# Generated by Django 3.1.1 on 2020-09-30 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0011_auto_20200930_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='picture',
            field=models.ImageField(default='/media/artist_picture/default-artist-placeholder.png', upload_to='artist_picture', verbose_name='Artist Picture'),
        ),
    ]
