# Generated by Django 3.1.1 on 2020-10-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0013_auto_20200930_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='description',
            field=models.TextField(blank=True, default='', max_length=500, verbose_name='Description'),
        ),
    ]
