# Generated by Django 3.1.1 on 2020-10-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0015_auto_20201002_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='song_file',
            new_name='src',
        ),
        migrations.AddField(
            model_name='song',
            name='popularity',
            field=models.IntegerField(default=0, verbose_name='Number of song plays'),
        ),
    ]
