version: "3.9"
   
services:
  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ./backend/.env.dev
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - es

  es:
    image: elasticsearch:7.8.1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/.env.dev


volumes:
  postgres_data:
  es_data: